### ISSUE TITLE
non zero value required

### ISSUE THREAD

**Issue by Narven** [asaskevich/govalidator#140]
I have a struct where Im validating with "required"

```
type BasicInfo struct {
        FirstName string `json:"first_name,omitempty" db:"first_name" valid:"alpha,required"`
        LastName  string `json:"last_name,omitempty" db:"last_name" valid:"alpha,required"`
        Gender    int    `json:"gender" db:"gender" valid:"required"`
    }
```

Why is that it gives me this error `non zero value required` if i pass 0 (zero) to Gender ? zero is not a value?

Thanks

**Comment by waltton** [comment]
If you say that a integer is required the only value that make sense to be considered as not valid is zero. But if you use a pointer to a integer that can be null the zero maybe considered as a valid value.

**Comment by andrewwatson** [comment]
In Go structs, the "zero value" of an int is 0.  It's impossible to know if someone created the struct without setting the value of the int or they deliberately used 0 as the value.  It seems like this test was designed to catch the former, not the latter.

Maybe instead of "required" it should be a "non-zero" validation?

**Comment by asaskevich** [comment]
Agree with @andrewwatson
`require` means existence of value but not zero equality

**Comment by tugbadartici** [comment]
Did you add this on code? How should I validate the non-zero fields? The "required" tag still does not work. Or, this won't be implemented? @asaskevich

**Comment by simonpoulin** [comment]
I had tried remove underscore and it worked for me
