### ISSUE TITLE
[]byte with one zero value fails required

### ISSUE THREAD

**Issue by vladimiroff** [asaskevich/govalidator#334]
```go
type Foo struct {
	ID   []byte `valid:"required"`
	Name string `valid:"required"`
}

func main() {
	f := Foo{
		ID:   []byte{93, 93, 0, 75},
		Name: "Foo",
	}

	if ok, err := valid.ValidateStruct(f); !ok {
		log.Fatalf("ok: %v; err: %v", ok, err)
	}
}
```

This fails because of the 3rd element in Foo.ID. Replacing it with any other value makes `required` pass.

This might make sense in general (i.e. all the values in given slice should NOT have a zero value), but it breaks `required` for UUIDs, for instance. UUID is really just a `[16]byte` and thus validating `Foo{ID: uuid.New()}` will be nondeterministic. Depends on whether `uuid.New` happened to generate UUID with at least one zero byte.

**Comment by mushegdavtyan** [comment]
I have the same bug. For example: for uuid "03691600-806c-11e9-b3d0-6c626de70856" govalidator return "non zero value required"

**Comment by Coderrob** [comment]
Created a test to cover the reported failure. Unable to reproduce using similar required value and input byte slice. Could be this was resolved in a more recent update since this issue was created. Can you all verify this behavior is still existing w/ latest code? https://github.com/asaskevich/govalidator/pull/373

**Comment by vladimiroff** [comment]
This seems to be fixed now. I have no idea when, though. Given that I've opened the issue and it is no longer reproducible, I'm closing it.
