### ISSUE TITLE
How to list errors by field

### ISSUE THREAD

**Issue by jeffutter** [asaskevich/govalidator#67]
I am wondering how to get errors for specific fields for the purpose of showing invalid input on a form. As far as I can gather ValidateStruct just returns a normal error object that is a string of all of the errors. Is there a way to get the errors for a specific field or am I missing something.

Thanks for any help.

**Comment by asaskevich** [comment]
At this moment it gives error like this: `Title: My123 does not validate as alpha;AuthorIP: 123 does not validate as ipv4;`. I create function `ErroByField(e error, field string)` that will return error for specified field of struct or empty string otherwise, I hope that it will be helpful. For example:
```go
type Post struct {
	Title    string `valid:"alpha,required"`
	Message  string `valid:"ascii"`
	AuthorIP string `valid:"ipv4"`
}

post := &Post{"My123", "duck13126", "123"}
result, err := govalidator.ValidateStruct(post)

titleError := govalidator.ErrorByField(err, "Title")
if titleError != "" {
    println(titleError) // -> My123 does not validate as alpha
}
```
You can reopen it if there are any problems with it
